#!/bin/bash
# getproject PROJECTs...
#
# If on a Jenkins server, enter the project path below and this script will pull sources from the project path, otherwise it will try to git clone/pull.  If cloning, you will need to enter the full http repo.

: ${PROJECTPATH:=/var/lib/jenkins/jobs}
: ${SOURCES:=sources}

if [ $# -eq 0 ]; then
    echo "Error: invalid syntax"
    echo "getproject <PROJECTs>..."
fi
if [ ! -d "$SOURCES" ]; then
    mkdir "$SOURCES"
fi

for projname in $@; do
    if [ -d $PROJECTPATH ]; then
        project=`ls $PROJECTPATH | grep "${projname}-src"`
        if [ -n "$project" ]; then
            if [ -d "$PROJECTPATH/$project/workspace/source" ]; then
                if [ -d "$SOURCES/$projname" ]; then
                    rm -rf "$SOURCES/$projname"
                fi
                printf "Get $projname ... "
                cp -r "$PROJECTPATH/$project/workspace/source" "$SOURCES/$projname"
                echo "[done]"
            else
                echo Error: $PROJECTPATH/$project/workspace/source does not exist
            fi
        else
            cd "$SOURCES"
            git clone $projname
            proj=`basename $projname`
            if [ ! -d "$SOURCES/$proj" ]; then
                echo "Error: $1 not found"
            fi
            cd -
        fi
    else
        proj=`basename $projname`
        if [ -d "$SOURCES/$proj" ]; then
            cd "$SOURCES/$proj"
            git pull
            cd -
        else
            cd "$SOURCES"
            git clone $projname
            if [ ! -d "$proj" ]; then
                echo Error: $1 was not found
            fi
            cd -
        fi
    fi
done
