#!/bin/bash
# Syntax:
#     installman <PATH>
#     installman
#
#     When PATH is not specified, the default path is "/usr/local/share/man"
#

: ${MANDIR:=/usr/local/share/man}

if [ $# -gt 0 ]; then
    manpath=$1
else
    manpath="$MANDIR"
fi

if [ ! -d "man" ]; then
    echo "Nothing to do: man pages are not available to install"
    exit
fi

if [ ! -d $manpath ]; then
    echo "creating '$manpath'"
    mkdir -p "$manpath"
fi

if [ ! -d $manpath ]; then
    echo "Error: path '$manpath' does not exist"
    exit
fi

> installed_man_pages.txt
for manpage in `find man | cut -d/ -f2- | grep / | sort -u`
do
    mantype=`echo $manpage | cut -d/ -f1`
    if [ ! -d "$manpath/$mantype" ]; then
        mkdir "$manpath/$mantype"
    fi
    cp "man/$manpage" "$manpath/$mantype"
    if [ -f "$manpath/$manpage" ]; then
        echo $manpage >> installed_man_pages.txt
    fi
done

if [ -s installed_man_pages.txt ]; then
    if [ -n `which mandb` ]; then
        echo "Updating man database"
        mandb $manpath
    else 
        echo "mandb tool not found, please verify that mandb (man) is installed"
    fi
else
    rm installed_man_pages.txt
    echo "No man pages were installed, man database was not updated"
fi
