#!/bin/bash

: ${DOXYGEN_FILE:=./Doxyfile.cfg}
: ${DOXYPYPY_PATH:=/usr/local/bin}

#verify doxypypy location
doxypypy_loc=`which doxypypy`
if [ -n "$doxypypy_loc" ]; then
    DOXYPYPY_PATH=`dirname $doxypypy_loc`
elif [ ! -e $DOXYPYPY_PATH/doxypypy ]; then
    echo "doxypypy was not found, please verify that doxypypy is installed"
    exit 1
fi

#generate documentation
if [ -z `which doxygen` ]; then
    echo "doxygen tool not found, please verify that Doxygen is installed"
    exit 1
fi
doxygen "$DOXYGEN_FILE"

#find "tool" man files and convert to type "1"
for manfile in `grep -r "@page" * | grep -v "code-documentation.md" | awk -F: '{ print $1 }' | grep -v -e "makedocs" -e "html/"`
do
    mancommand=`basename "${manfile%.*}"`
    ./setmantype "$mancommand" 1
done

#remove the man directory references
grep -ri "Directory Reference" man | awk -F: '{ print $1 }' | sort -u | xargs -i rm {}
